### ISSUE TITLE
BeautyList causes major slow down.

### ISSUE THREAD

**Issue by Craftomega** [lzinga/ComLib#4]
https://github.com/lzinga/ComLib/blob/master/ComLib.Unity/Editor/BeautyList.cs

If you are placing objects into a list and watching it at the same time it causes unity to slow down to a crawl. I would recommend having a disable function for BeautyList.

I would in fact recommend a complete removal of BeautyList from ComLib as most other functions are needed additions where BeautyList is a fundamental change to how unity operates lists.

**Comment by Janooba** [comment]
See latest commit. All editor scripts/extensions have been moved to the ComLib.Unity.Editor library.
